theme: minima
title: bzllzw's blog
# author: bzllzw
# email: bzllzw@foxmail.com
# description: > # this means to ignore newlines until "baseurl:"
# banzenglin linzhengwei
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  bzllzw # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
